### PR TITLE
Small fix in dev docs

### PR DESCRIPTION
**Pull request by SkySonR**
latest version generate config with .ts extension

### CODE REVIEW

**Comment by rightjelkin** [comment]
@SkySonR Hello, thanks for your comment! Yes, it needs to be fixed. But could you please fix other same mistakes in this file within this PR? I can see couple more wrong extensions of this file. We would be grateful.

**Review by rightjelkin — CHANGES_REQUESTED** [review]
I have commented a request already. Kindly please check it

**Comment by SkySonR** [comment]
> @SkySonR Hello, thanks for your comment! Yes, it needs to be fixed. But could you please fix other same mistakes in this file within this PR? I can see couple more wrong extensions of this file. We would be grateful.

Thanks, I will do

**Comment by SkySonR** [comment]
@rightjelkin all content updated accordantly changes in latest versions

**Comment by rightjelkin** [comment]
Thank you, I will check. Now I have a problem with a latest locklift version initialization (error if typescript hasn't been intialized). I have already connected with locklift developers, waiting for fix and then I will accept this PR 👍

**Review by rightjelkin — APPROVED** [review]

**Comment by rightjelkin** [comment]
Al necessary points fixed by [this](https://github.com/venom-blockchain/venom-blockchain.github.io/pull/85) PR

**Pull request closed without merging**
